In [4]:
import pandas as pd
matches = pd.read_csv("../data/raw/results.csv")
matches.tail(12)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49490,2026-07-03,Australia,Egypt,1.0,1.0,FIFA World Cup,Arlington,United States,True
49491,2026-07-03,Argentina,Cape Verde,3.0,2.0,FIFA World Cup,Miami Gardens,United States,True
49492,2026-07-03,Colombia,Ghana,1.0,0.0,FIFA World Cup,Kansas City,United States,True
49493,2026-07-04,Canada,Morocco,0.0,3.0,FIFA World Cup,Houston,United States,True
49494,2026-07-04,Paraguay,France,0.0,1.0,FIFA World Cup,Philadelphia,United States,True
49495,2026-07-05,Brazil,Norway,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49496,2026-07-05,Mexico,England,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49497,2026-07-06,Portugal,Spain,NaN,NaN,FIFA World Cup,Dallas,United States,True
49498,2026-07-06,United States,Belgium,NaN,NaN,FIFA World Cup,Seattle,United States,False
49499,2026-07-06,Argentina,Egypt,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49500,2026-07-06,Switzerland,Colombia,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True

In [5]:
matches.shape

(49502, 9)

In [6]:
matches.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

In [7]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49502 entries, 0 to 49501
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49502 non-null  object
 1   home_team   49502 non-null  object
 2   away_team   49502 non-null  object
 3   home_score  49495 non-null  float64
 4   away_score  49495 non-null  float64
 5   tournament  49502 non-null  object
 6   city        49502 non-null  object
 7   country     49502 non-null  object
 8   neutral     49502 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [8]:
matches.describe()

         home_score    away_score
count  49495.000000  49495.000000
mean       1.757268      1.181837
std        1.773877      1.401639
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [9]:
matches.isnull().sum()

date          0
home_team     0
away_team     0
home_score    7
away_score    7
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [10]:
matches["tournament"].value_counts()

tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1061
                                        ...
Copa Confraternidad                         1
ConIFA Challenger Cup                       1
Benedikt Fontana Cup                        1
CONIFA World Cup qualification              1
South Asian Super Cup                       1
Name: count, Length: 200, dtype: int64

In [11]:
matches["home_team"].nunique()

327

In [12]:
matches["away_team"].nunique()

321

In [13]:
matches["date"].min()

'1872-11-30'

In [14]:
matches["date"].max()

'2026-07-09'

In [15]:
world_cup = matches[matches["tournament"] == "FIFA World Cup"]
world_cup.tail(20)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49482,2026-06-30,France,Sweden,3.0,0.0,FIFA World Cup,East Rutherford,United States,True
49483,2026-06-30,Mexico,Ecuador,2.0,0.0,FIFA World Cup,Mexico City,Mexico,False
49484,2026-07-01,England,DR Congo,2.0,1.0,FIFA World Cup,Atlanta,United States,True
49485,2026-07-01,Belgium,Senegal,3.0,2.0,FIFA World Cup,Seattle,United States,True
49486,2026-07-01,United States,Bosnia and Herzegovina,2.0,0.0,FIFA World Cup,Santa Clara,United States,False
49487,2026-07-02,Spain,Austria,3.0,0.0,FIFA World Cup,Inglewood,United States,True
49488,2026-07-02,Portugal,Croatia,2.0,1.0,FIFA World Cup,Toronto,Canada,True
49489,2026-07-02,Switzerland,Algeria,2.0,0.0,FIFA World Cup,Vancouver,Canada,True
49490,2026-07-03,Australia,Egypt,1.0,1.0,FIFA World Cup,Arlington,United States,True
49491,2026-07-03,Argentina,Cape Verde,3.0,2.0,FIFA World Cup,Miami Gardens,United States,True
49492,2026-07-03,Colombia,Ghana,1.0,0.0,FIFA World Cup,Kansas City,United States,True
49493,2026-07-04,Canada,Morocco,0.0,3.0,FIFA World Cup,Houston,United States,True
49494,2026-07-04,Paraguay,France,0.0,1.0,FIFA World Cup,Philadelphia,United States,True
49495,2026-07-05,Brazil,Norway,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49496,2026-07-05,Mexico,England,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49497,2026-07-06,Portugal,Spain,NaN,NaN,FIFA World Cup,Dallas,United States,True
49498,2026-07-06,United States,Belgium,NaN,NaN,FIFA World Cup,Seattle,United States,False
49499,2026-07-06,Argentina,Egypt,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49500,2026-07-06,Switzerland,Colombia,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True

In [22]:
played_matches = matches.dropna(subset=["home_score","away_score"])

future_matches = matches[matches["home_score"].isna()]
future_matches

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49495,2026-07-05,Brazil,Norway,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49496,2026-07-05,Mexico,England,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49497,2026-07-06,Portugal,Spain,NaN,NaN,FIFA World Cup,Dallas,United States,True
49498,2026-07-06,United States,Belgium,NaN,NaN,FIFA World Cup,Seattle,United States,False
49499,2026-07-06,Argentina,Egypt,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49500,2026-07-06,Switzerland,Colombia,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True

In [25]:
played_matches.shape

(49495, 9)