## Only for exploring the data

## Data Loading and interpreting tables of the CSV file "results.csv".

### Loading the dataset and playing around with it!

In [4]:
import pandas as pd
matches = pd.read_csv("../data/raw/results.csv")
matches.tail(12)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49490,2026-07-03,Australia,Egypt,1.0,1.0,FIFA World Cup,Arlington,United States,True
49491,2026-07-03,Argentina,Cape Verde,3.0,2.0,FIFA World Cup,Miami Gardens,United States,True
49492,2026-07-03,Colombia,Ghana,1.0,0.0,FIFA World Cup,Kansas City,United States,True
49493,2026-07-04,Canada,Morocco,0.0,3.0,FIFA World Cup,Houston,United States,True
49494,2026-07-04,Paraguay,France,0.0,1.0,FIFA World Cup,Philadelphia,United States,True
49495,2026-07-05,Brazil,Norway,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49496,2026-07-05,Mexico,England,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49497,2026-07-06,Portugal,Spain,NaN,NaN,FIFA World Cup,Dallas,United States,True
49498,2026-07-06,United States,Belgium,NaN,NaN,FIFA World Cup,Seattle,United States,False
49499,2026-07-06,Argentina,Egypt,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49500,2026-07-06,Switzerland,Colombia,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True

In [5]:
matches.shape

(49502, 9)

In [6]:
matches.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

In [7]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49502 entries, 0 to 49501
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49502 non-null  object
 1   home_team   49502 non-null  object
 2   away_team   49502 non-null  object
 3   home_score  49495 non-null  float64
 4   away_score  49495 non-null  float64
 5   tournament  49502 non-null  object
 6   city        49502 non-null  object
 7   country     49502 non-null  object
 8   neutral     49502 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [8]:
matches.describe()

         home_score    away_score
count  49495.000000  49495.000000
mean       1.757268      1.181837
std        1.773877      1.401639
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [9]:
matches.isnull().sum()

date          0
home_team     0
away_team     0
home_score    7
away_score    7
tournament    0
city          0
country       0
neutral       0
dtype: int64

### Counting the number of tournaments

In [10]:
matches["tournament"].value_counts()

tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1061
                                        ...
Copa Confraternidad                         1
ConIFA Challenger Cup                       1
Benedikt Fontana Cup                        1
CONIFA World Cup qualification              1
South Asian Super Cup                       1
Name: count, Length: 200, dtype: int64

### Number of unique teams

In [11]:
matches["home_team"].nunique()

327

In [12]:
matches["away_team"].nunique()

321

### Earliest and latest match

In [13]:
matches["date"].min()

'1872-11-30'

In [14]:
matches["date"].max()

'2026-07-09'

### Check World Cup matches

In [15]:
world_cup = matches[matches["tournament"] == "FIFA World Cup"]
world_cup.tail(20)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49482,2026-06-30,France,Sweden,3.0,0.0,FIFA World Cup,East Rutherford,United States,True
49483,2026-06-30,Mexico,Ecuador,2.0,0.0,FIFA World Cup,Mexico City,Mexico,False
49484,2026-07-01,England,DR Congo,2.0,1.0,FIFA World Cup,Atlanta,United States,True
49485,2026-07-01,Belgium,Senegal,3.0,2.0,FIFA World Cup,Seattle,United States,True
49486,2026-07-01,United States,Bosnia and Herzegovina,2.0,0.0,FIFA World Cup,Santa Clara,United States,False
49487,2026-07-02,Spain,Austria,3.0,0.0,FIFA World Cup,Inglewood,United States,True
49488,2026-07-02,Portugal,Croatia,2.0,1.0,FIFA World Cup,Toronto,Canada,True
49489,2026-07-02,Switzerland,Algeria,2.0,0.0,FIFA World Cup,Vancouver,Canada,True
49490,2026-07-03,Australia,Egypt,1.0,1.0,FIFA World Cup,Arlington,United States,True
49491,2026-07-03,Argentina,Cape Verde,3.0,2.0,FIFA World Cup,Miami Gardens,United States,True
49492,2026-07-03,Colombia,Ghana,1.0,0.0,FIFA World Cup,Kansas City,United States,True
49493,2026-07-04,Canada,Morocco,0.0,3.0,FIFA World Cup,Houston,United States,True
49494,2026-07-04,Paraguay,France,0.0,1.0,FIFA World Cup,Philadelphia,United States,True
49495,2026-07-05,Brazil,Norway,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49496,2026-07-05,Mexico,England,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49497,2026-07-06,Portugal,Spain,NaN,NaN,FIFA World Cup,Dallas,United States,True
49498,2026-07-06,United States,Belgium,NaN,NaN,FIFA World Cup,Seattle,United States,False
49499,2026-07-06,Argentina,Egypt,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49500,2026-07-06,Switzerland,Colombia,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True

### First I'll separate played vs unplayed matches

In [22]:
played_matches = matches.dropna(subset=["home_score","away_score"])

future_matches = matches[matches["home_score"].isna()]
future_matches

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49495,2026-07-05,Brazil,Norway,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49496,2026-07-05,Mexico,England,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49497,2026-07-06,Portugal,Spain,NaN,NaN,FIFA World Cup,Dallas,United States,True
49498,2026-07-06,United States,Belgium,NaN,NaN,FIFA World Cup,Seattle,United States,False
49499,2026-07-06,Argentina,Egypt,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49500,2026-07-06,Switzerland,Colombia,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True

In [25]:
played_matches.shape

(49495, 9)

### Create the target column (0=Away Win, 1=Draw, 2=Home Win)

In [26]:
def get_match_result(row):
    if row["home_score"] > row["away_score"]:
        return 2      # Home Win
    elif row["home_score"] < row["away_score"]:
        return 0      # Away Win
    else:
        return 1      # Draw


played_matches["target"] = played_matches.apply(get_match_result, axis=1)

C:\Users\user\AppData\Local\Temp\ipykernel_43836\1653084028.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  played_matches["target"] = played_matches.apply(get_match_result, axis=1)

In [27]:
played_matches.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,target
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,1
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,2
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,2
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,1
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,2

### Check class balance to know whether the dataset is balanced or not.

In [28]:
played_matches["target"].value_counts()

target
2    24256
0    13983
1    11256
Name: count, dtype: int64

In [29]:
played_matches["target"].value_counts(normalize=True)

target
2    0.490070
0    0.282513
1    0.227417
Name: proportion, dtype: float64

### Convert the date data into a proper datetime

In [30]:
played_matches["date"] = pd.to_datetime(played_matches["date"])

C:\Users\user\AppData\Local\Temp\ipykernel_43836\734226211.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  played_matches["date"] = pd.to_datetime(played_matches["date"])

In [31]:
played_matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49495 entries, 0 to 49494
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49495 non-null  datetime64[ns]
 1   home_team   49495 non-null  object
 2   away_team   49495 non-null  object
 3   home_score  49495 non-null  float64
 4   away_score  49495 non-null  float64
 5   tournament  49495 non-null  object
 6   city        49495 non-null  object
 7   country     49495 non-null  object
 8   neutral     49495 non-null  bool
 9   target      49495 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 3.8+ MB

### Sort the matches

In [32]:
played_matches = played_matches.sort_values("date")

In [33]:
played_matches.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,target
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,1
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,2
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,2
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,1
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,2

In [34]:
played_matches.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,target
49491,2026-07-03,Argentina,Cape Verde,3.0,2.0,FIFA World Cup,Miami Gardens,United States,True,2
49490,2026-07-03,Australia,Egypt,1.0,1.0,FIFA World Cup,Arlington,United States,True,1
49492,2026-07-03,Colombia,Ghana,1.0,0.0,FIFA World Cup,Kansas City,United States,True,2
49493,2026-07-04,Canada,Morocco,0.0,3.0,FIFA World Cup,Houston,United States,True,0
49494,2026-07-04,Paraguay,France,0.0,1.0,FIFA World Cup,Philadelphia,United States,True,0

### Reset the index

In [35]:
played_matches = played_matches.reset_index(drop=True)

### Create a column that indicates whether the match was played on neutral ground.

In [37]:
played_matches["neutral"] = played_matches["neutral"].astype(int)

In [47]:
played_matches[["home_team", "away_team", "tournament", "neutral"]].tail()

       home_team   away_team      tournament  neutral
49490  Argentina  Cape Verde  FIFA World Cup        1
49491  Australia       Egypt  FIFA World Cup        1
49492   Colombia       Ghana  FIFA World Cup        1
49493     Canada     Morocco  FIFA World Cup        1
49494   Paraguay      France  FIFA World Cup        1

### Save the cleaned dataset

In [48]:
played_matches.to_csv(
    "../data/processed/played_matches.csv",
    index=False
)

### Now let's import the get_team_history function that we created inside feature directory that return the matches for specific teams before a certain date.

In [79]:
import os
import sys

PROJECT_ROOT = os.path.abspath("..")

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

In [82]:
from src.features.team_stats import get_team_history

#### Let's see Egypt matches before Argentina match

In [83]:
get_team_history(played_matches, "Egypt", pd.Timestamp("2026-07-05")).tail(10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,target
49106,2026-01-14,Senegal,Egypt,1.0,0.0,African Cup of Nations,Tangier,Morocco,1,2
49108,2026-01-17,Egypt,Nigeria,0.0,0.0,African Cup of Nations,Casablanca,Morocco,1,1
49173,2026-03-27,Saudi Arabia,Egypt,0.0,4.0,Friendly,Jeddah,Saudi Arabia,0,0
49219,2026-03-31,Spain,Egypt,0.0,0.0,Friendly,Barcelona,Spain,0,1
49265,2026-05-28,Egypt,Russia,1.0,0.0,Friendly,Cairo,Egypt,0,2
49358,2026-06-06,Brazil,Egypt,2.0,1.0,Friendly,Cleveland,United States,1,2
49419,2026-06-15,Belgium,Egypt,1.0,1.0,FIFA World Cup,Seattle,United States,1,1
49442,2026-06-21,New Zealand,Egypt,1.0,3.0,FIFA World Cup,Vancouver,Canada,1,0
49465,2026-06-26,Egypt,Iran,1.0,1.0,FIFA World Cup,Seattle,United States,1,1
49491,2026-07-03,Australia,Egypt,1.0,1.0,FIFA World Cup,Arlington,United States,1,1

In [90]:
import importlib
import src.features.team_stats as team_stats

importlib.reload(team_stats)

In [91]:
from src.features.team_stats import get_matches_played

In [102]:
get_matches_played(
    played_matches,
    "Egypt",
    pd.Timestamp("2026-07-05")
)

760

In [106]:
import importlib
import src.features.team_stats as team_stats

importlib.reload(team_stats)

In [98]:
from src.features.team_stats import get_wins

In [103]:
get_wins(
    played_matches,
    "Egypt",
    pd.Timestamp("2026-07-05")
)

380

### Let's add more helper functions

#### Functions are created in **team_stats.py**

In [109]:
from src.features.team_stats import get_average_goals_scored, get_average_goals_conceded, get_win_rate

In [112]:
get_average_goals_scored(
    played_matches,
    "Egypt",
    pd.Timestamp("2026-07-05")
)

1.6197368421052631

In [113]:
get_average_goals_conceded(
    played_matches,
    "Egypt",
    pd.Timestamp("2026-07-05")
)

1.013157894736842

In [114]:
get_win_rate(
    played_matches,
    "Egypt",
    pd.Timestamp("2026-07-05")
)

0.5

## Now we need to build the Feature Generator
#### Create one function that takes a match like: (Brazil vs England), (Date: 2026-07-05) and returns: Home matches played, Away matches played, Home wins, Away wins, Home win rate, ....
#### This row is what the ML model will learn from.
#### Machine learning algorithms cannot understand team names. To the model: Brazil, Egypt are just words.

#### Features created at **src/features/feature_generator.py**

Let's test it here

In [121]:
test_match = future_matches.iloc[0]

test_match

date               2026-07-05
home_team              Brazil
away_team              Norway
home_score                NaN
away_score                NaN
tournament     FIFA World Cup
city          East Rutherford
country         United States
neutral                  True
Name: 49495, dtype: object

In [122]:
from src.features.feature_generator import create_match_features

features = create_match_features(
    played_matches,
    test_match
)

features

{'home_matches': 1063, 'away_matches': 876}